apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincode-deployment
  namespace: bitirme-app
  labels:
    app: chaincode-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaincode-service
  template:
    metadata:
      labels:
        app: chaincode-service
    spec:
      nodeName: pardus
      imagePullSecrets:
        - name: gitlab-reg-cred
      containers:
        - name: chaincode-container
          image: 172.28.6.240:32003/kerem-bitirme/images/chaincode:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:9999"
            # BURAYA GERÇEK CHAINCODE_ID GELİCEK
            - name: CHAINCODE_ID
              value: "basic_1.0:7d72d14db566c6596bb3c5be12a0165948513dcf58b36cfca4a30593ad61b161"
          readinessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: bitirme-app
  name: chaincode-service
spec:
  selector:
    app: chaincode-service
  ports:
    - protocol: TCP
      port: 9999        # Cluster içinden erişilen port
      targetPort: 9999  # Konteynerin (Node.js) içindeki port
  type: ClusterIP
