apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricCA
metadata:
  name: ca-student
  namespace: fabric-bevel
spec:
  image: hyperledger/fabric-ca
  version: 1.5.6
  debug: true
  hosts:
    - localhost
    - ca-student
    - ca-student.fabric-bevel
    - ca-student.fabric-bevel.svc.cluster.local
  service:
    type: ClusterIP
  storage:
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: local-path
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 128Mi
  ca:
    bccsp:
      default: SW
      sw:
        hash: SHA2
        security: '256'
    cfg:
      affiliations:
        allowRemove: true
      identities:
        allowRemove: true
    crl:
      expiry: 24h
    csr:
      ca:
        expiry: 131400h
        pathLength: 0
      cn: ca
      hosts:
        - localhost
      names:
        - C: TR
          L: ''
          O: StudentOrg
          OU: ''
          ST: ''
    intermediate:
      parentServer:
        caName: ''
        url: ''
    name: ca
    registry:
      identities:
        - affiliation: ''
          attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: admin
          pass: adminpw
          type: client
      max_enrollments: -1
    subject:
      C: TR
      L: Istanbul
      O: StudentOrg
      OU: ''
      ST: ''
      cn: ca
  clrSizeLimit: 512000
  cors:
    enabled: false
    origins: []
  db:
    datasource: fabric-ca-server.db
    type: sqlite3
  metrics:
    provider: prometheus
    statsd:
      address: '127.0.0.1:8125'
      network: udp
      prefix: server
      writeInterval: 10s
  rootCA:
    subject:
      C: TR
      L: Istanbul
      O: StudentOrg
      OU: ''
      ST: ''
      cn: ca
  tlsCA:
    bccsp:
      default: SW
      sw:
        hash: SHA2
        security: '256'
    cfg:
      affiliations:
        allowRemove: true
      identities:
        allowRemove: true
    crl:
      expiry: 24h
    csr:
      ca:
        expiry: 131400h
        pathLength: 0
      cn: tlsca
      hosts:
        - localhost
      names:
        - C: TR
          L: ''
          O: StudentOrg
          OU: ''
          ST: ''
    intermediate:
      parentServer:
        caName: ''
        url: ''
    name: tlsca
    registry:
      identities:
        - affiliation: ''
          attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: admin
          pass: adminpw
          type: client
      max_enrollments: -1
    subject:
      C: TR
      L: Istanbul
      O: StudentOrg
      OU: ''
      ST: ''
      cn: tlsca
