apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricMainChannel
metadata:
  name: demo
  namespace: fabric-bevel
spec:
  name: demo
  adminOrdererOrganizations:
    - mspID: OrdererOrgMSP
  adminPeerOrganizations:
    - mspID: AdminOrgMSP
  channelConfig:
    application:
      acls: null
      capabilities:
        - V2_0
      policies: null
    capabilities:
      - V2_0
    orderer:
      batchSize:
        absoluteMaxBytes: 10485760
        maxMessageCount: 10
        preferredMaxBytes: 524288
      batchTimeout: 2s
      capabilities:
        - V2_0
      etcdRaft:
        options:
          electionTick: 10
          heartbeatTick: 1
          maxInflightBlocks: 5
          snapshotIntervalSize: 16777216
          tickInterval: 500ms
      ordererType: etcdraft
      policies: null
      state: STATE_NORMAL
    policies: null
  externalOrdererOrganizations: []
  peerOrganizations:
    - mspID: AdminOrgMSP
      caName: ca-admin
      caNamespace: fabric-bevel
    - mspID: StudentOrgMSP
      caName: ca-student
      caNamespace: fabric-bevel
  identities:
    OrdererOrgMSP:
      secretKey: user.yaml
      secretName: orderer-admin
      secretNamespace: fabric-bevel
    AdminOrgMSP:
      secretKey: user.yaml
      secretName: adminorg-admin
      secretNamespace: fabric-bevel
  externalPeerOrganizations: []
  ordererOrganizations:
    - caName: ca-orderer
      caNamespace: fabric-bevel
      externalOrderersToJoin: []
      mspID: OrdererOrgMSP
      orderersToJoin:
        - name: orderer-orderer0
          namespace: fabric-bevel
  orderers:
    - host: orderer-orderer0.fabric-bevel.svc.cluster.local
      port: 7050
      tlsCert: ""
