apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricOrderingService
metadata:
  name: orderer
  namespace: fabric-bevel
spec:
  image: hyperledger/fabric-orderer
  tag: 2.5.0
  mspID: OrdererOrgMSP
  enrollment:
    component:
      cahost: ca-orderer.fabric-bevel.svc.cluster.local
      caname: ca
      caport: 7054
      catls:
        cacert: ""
      enrollid: admin
      enrollsecret: adminpw
    tls:
      cahost: ca-orderer.fabric-bevel.svc.cluster.local
      caname: tlsca
      caport: 7054
      catls:
        cacert: ""
      enrollid: admin
      enrollsecret: adminpw
      csr:
        hosts: []
  nodes:
    - id: orderer0
      enrollment:
        tls:
          csr:
            hosts:
              - orderer0
              - orderer0.fabric-bevel.svc.cluster.local
  service:
    type: ClusterIP
  storage:
    size: 5Gi
    storageClass: local-path
    accessMode: ReadWriteOnce
  systemChannel:
    name: system-channel
    config:
      absoluteMaxBytes: 10485760
      applicationCapabilities:
        V2_0: true
      batchTimeout: 2s
      channelCapabilities:
        V2_0: true
      electionTick: 10
      heartbeatTick: 1
      maxInflightBlocks: 5
      maxMessageCount: 500
      ordererCapabilities:
        V2_0: true
      preferredMaxBytes: 2097152
      snapshotIntervalSize: 19
      tickInterval: 500ms
