apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-student-peer
  namespace: fabric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-peer
  template:
    metadata:
      labels:
        app: student-peer
    spec:
      nodeSelector:
        storage: longhorn
      containers:
        - name: peer
          image: hyperledger/fabric-peer:2.5
          env:
            - name: CORE_CHAINCODE_EXTERNALBUILDERS
              value: '[{"path":"/builders/external","name":"external-builder","propagateEnvironment":["CHAINCODE_CCID"]}]'
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_ID
              value: peer0.StudentOrg.com
            - name: CORE_PEER_ADDRESS
              value: svc-student-peer:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_CHAINCODEADDRESS
              value: svc-student-peer:7052
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: svc-student-peer:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: svc-student-peer:7051
            - name: CORE_PEER_LOCALMSPID
              value: StudentOrgMSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /crypto-config/organizations/peerOrganizations/StudentOrg.com/peers/peer0.StudentOrg.com/msp
            # --- TLS AyarlarÄ± ---
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /crypto-config/organizations/peerOrganizations/StudentOrg.com/peers/peer0.StudentOrg.com/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /crypto-config/organizations/peerOrganizations/StudentOrg.com/peers/peer0.StudentOrg.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /crypto-config/organizations/peerOrganizations/StudentOrg.com/peers/peer0.StudentOrg.com/tls/ca.crt
          ports:
            - containerPort: 7051
            - containerPort: 7052
          volumeMounts:
            - name: peer-storage
              mountPath: /crypto-config
            - name: external-builder
              mountPath: /builders/external/bin
      volumes:
        - name: peer-storage
          persistentVolumeClaim:
            claimName: pvc-crypto-rwx
        - name: external-builder
          configMap:
            name: external-builder-scripts
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: svc-student-peer
  namespace: fabric
spec:
  type: ClusterIP
  selector:
    app: student-peer
  ports:
    - name: grpc
      port: 7051
      targetPort: 7051
    - name: chaincode
      port: 7052
      targetPort: 7052
